[package]
name = "editor"
edition.workspace = true
version.workspace = true

[[bin]]
name = "map-editor"
path = "src/main.rs"

[dependencies]
archive = { path = "../archive" }
map = { path = "../map" }
render = { path = "../render" }
eframe = "0.33"
rfd = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
